### PR TITLE
add yet another webpack plugin

### PR DESCRIPTION
**Pull request by MaxGraey**
With supporting async batching

### CODE REVIEW

**Comment by Apercu** [comment]
What's the point of duplicating things exactly?

**Comment by MaxGraey** [comment]
Different implementation

**Comment by MaxGraey** [comment]
For example:
const ButternutWebpackPlugin = require('butternut-webpack-plugin').default;
vs
const ButternutPlugin = require('webpack-butternut-plugin');

+ slightly better bundle size
+ speedup for large number of chunks

**Comment by Apercu** [comment]
Comparing the require import is not very an improvement.

Any benchmarks? PRs exists for a reason too.

**Comment by MaxGraey** [comment]
@Apercu Actually I started of working one week ago and about your implementation I find out only later. Anyway I don't see a problem for example webpack's UglifyJS has three different implementation as minimum

**Pull request closed without merging**
